version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.14-latest
    volumes:
      - ./front_envoy/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - 8080:80
      - 9901:9901
    command: /usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'front-envoy' --service-node 'front-envoy'

  service_a_envoy:
    image: envoyproxy/envoy-alpine:v1.14-latest
    volumes:
      - ./service_a/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - 8181:8181
    command: /usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-a' --service-node 'service-a'

  service_a:
    build: service_a/
    ports:
      - 8081:8081

  service_b_envoy:
    image: envoyproxy/envoy-alpine:v1.14-latest
    volumes:
      - ./service_b/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - 8182:8182
    command: /usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-b' --service-node 'service-b'

  service_b:
    build: service_b/
    ports:
      - 8082:8082

  service_c_envoy:
    image: envoyproxy/envoy-alpine:v1.14-latest
    volumes:
      - ./service_c/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - 8183:8183
    command: /usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-c' --service-node 'service-c'

  service_c:
    build: service_c/
    ports:
      - 8083:8083

